---
title: "ggplot_JS"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Load packages
```{r}
library(leaflet)
library(dplyr)
library(tidyr)
library(ggplot2)
library(DT)
library(scales) # install.packages("scales")
library(patchwork) # install.packages("patchwork")
```


#Load data (give URL, then check if on computer, if not - get from URL)
```{r}
data_url <- "https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e"

esc <- tryCatch(
    read.csv("data/escapement.csv", stringsAsFactors = FALSE),
    error=function(cond) {
        message(paste("Escapement file does not seem to exist, so get it from the KNB."))
        esc <- read.csv(url(data_url, method = "libcurl"), stringsAsFactors = FALSE)
        return(esc)
    }
)

head(esc)
```


#Data processing (split dates - convert year to numerals - filter to subset)
```{r}
annual_esc <- esc %>%
  separate(sampleDate, c("Year", "Month", "Day"), sep = "-") %>% 
  mutate(Year = as.numeric(Year)) %>% 
  group_by(Species, SASAP.Region, Year) %>% 
  summarise(escapement = sum(DailyCount)) %>% 
  filter(Species %in% c("Chinook", "Sockeye", "Chum", "Coho", "Pink"))

head(annual_esc)
```


#Data visualisation - first look at the data
```{r}
ggplot(annual_esc, aes(x = Species, y = escapement)) +
  geom_col()
```


#Changing colour of bars
```{r}
ggplot(annual_esc, aes(x = Species, y = escapement)) +
  geom_col(fill = "blue")
```


#Plot by species and region
```{r}
ggplot(annual_esc, aes(x = Species, y = escapement, fill = SASAP.Region)) +
  geom_col()
```


#Looking at Kodiak region time-series
```{r}
annual_esc %>% 
  filter(SASAP.Region == "Kodiak") %>% 
  ggplot(aes(x = Year, y = escapement, color = Species)) +
  geom_line() +
  geom_point() +
  ggtitle("Salmon Escapement for the Kodiak Region") +
  ylab("Escapement") +
  xlab("Year") +
  my_theme
  #theme_bw() +
 #theme(plot.title = element_text(hjust=0.5), 
  #      legend.position = "bottom") +
  #theme(legend.title = element_blank())
  
```


```{r}
my_theme <- theme_bw() +
  theme(plot.title = element_text(hjust=0.5), legend.position = "bottom", legend.title = element_blank())
```


#Playing with facet
```{r}
ggplot(annual_esc, aes(x = Year, y = escapement, color = Species)) + 
    geom_line() +
    geom_point() +
    scale_y_continuous(labels = comma) +
    facet_wrap(~SASAP.Region, scales = "free_y", ncol = 2) +
    ylab("Escapement") +
    my_theme
```


#Using patchwork to display multiple plots
```{r}
library(patchwork)
p1 <- ggplot(annual_esc, aes(x = Species, y = escapement)) +
  geom_col()

p1

p2 <- ggplot(annual_esc, aes(x = Species, y = escapement)) +
  geom_col(fill = "blue")

p2

p1 + p2
```

