---
title: "Spatial_analysis_JS"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


#Load packages
```{r}
library(sf)
library(dplyr)
library(ggplot2)
library(scales)
library(ggmap) #incorporating base maps into r vector maps
library(leaflet)
```


#Read in data
```{r}
ak_regions <-read_sf("data/ak_regions_simp.shp")

#plot(ak_regions)

#class(ak_regions)

#head(ak_regions)

st_crs(ak_regions)
```

#Reproject to Alaska ALbers (EPSG3338)
```{r}
ak_regions_3338 <- ak_regions %>% 
  st_transform(crs = 3338)

st_crs(ak_regions_3338)

plot(ak_regions_3338)
```

#Select by attributes 
```{r}
SE <- ak_regions_3338 %>% 
  filter(region == "Southeast") %>%
  select(region)

plot(SE)
```


#Spatial joins and summaries
```{r}
pop <- read.csv("data/alaska_population.csv", stringsAsFactors = F)

head(pop)

#Unless you are told the coordinate system for lat/long, bet on WGS84 (4326)

pop_4326 <- st_as_sf(pop, 
                     coords = c("lng", "lat"), 
                     crs = 4326, 
                     remove = F)

head(pop_4326)
```

```{r}
#pop_joined <- st_join(pop_4326, ak_regions_3338, join = st_within)
#Coordinate systems not the same = error

pop_3338 <- pop_4326 %>% 
  st_transform(crs = 3338)

pop_joined <- st_join(pop_3338, ak_regions_3338, join = st_within)

head(pop_joined)
```


#Calculate total population by region
```{r}
pop_region <- pop_joined %>%
  as.data.frame() %>% 
  group_by(region) %>% 
  summarise(total_pop = sum(population))

head(pop_region)
```

```{r}
#Join table (pop_region) and region shapefile (common attribute = region)
pop_region_3338 <- left_join(ak_regions_3338, pop_region, by = "region")
head(pop_region_3338)
plot(pop_region_3338["total_pop"])

#save file (delete_layer = overwrite saved file)
write_sf(pop_region_3338, "data/ak_regions_pop.shp", delete_layer = TRUE)
```


#Make maps!
```{r}
rivers_3338 <- read_sf("data/ak_rivers_simp.shp", stringsAsFactors = F)
head(rivers_3338)
```

```{r}
ggplot() +
  geom_sf(data=pop_region_3338, aes(fill = total_pop))+
  geom_sf(data = rivers_3338, aes(size = StrOrder), color = "blue")+
  geom_sf(data=pop_3338, aes(), size = 0.2, color = "navy")+
  scale_size(range = c(0.01, 0.2), guide = F)+
  theme_bw()+
  labs(fill = "Total Population")+
  scale_fill_continuous(low = "khaki", high = "firebrick", labels = comma)
```


#Getting basemap using ggmap (note - google products etc. use EPSG 3857)
```{r}
pop_3857 <- pop_3338 %>% 
  st_transform(crs=3857)
```

```{r}
# Define a function to fix the bbox to be in EPSG:3857
# See https://github.com/dkahle/ggmap/issues/160#issuecomment-397055208
ggmap_bbox_to_3857 <- function(map) {
  if (!inherits(map, "ggmap")) stop("map must be a ggmap object")
  # Extract the bounding box (in lat/lon) from the ggmap to a numeric vector, 
  # and set the names to what sf::st_bbox expects:
  map_bbox <- setNames(unlist(attr(map, "bb")), 
                       c("ymin", "xmin", "ymax", "xmax"))
  
  # Coonvert the bbox to an sf polygon, transform it to 3857, 
  # and convert back to a bbox (convoluted, but it works)
  bbox_3857 <- st_bbox(st_transform(st_as_sfc(st_bbox(map_bbox, crs = 4326)), 3857))
  
  # Overwrite the bbox of the ggmap object with the transformed coordinates 
  attr(map, "bb")$ll.lat <- bbox_3857["ymin"]
  attr(map, "bb")$ll.lon <- bbox_3857["xmin"]
  attr(map, "bb")$ur.lat <- bbox_3857["ymax"]
  attr(map, "bb")$ur.lon <- bbox_3857["xmax"]
  map
}
```

```{r}
bbox <- c(-170, 52, -130, 64) #SE Alaska
ak_map <- get_stamenmap(bbox, zoom=4)
ak_map_3857 <- ggmap_bbox_to_3857(ak_map)
```

```{r}
ggmap(ak_map_3857)+
  geom_sf(data = pop_3857, aes(color = population), inherit.aes = F)+
  scale_color_continuous(low = "khaki", high = "firebrick", labels = comma)
```


#Interactive maps using leaflet
```{r}
#Define leaflet projection (inputs must be EPSG4326 - but then reprojects eg to 3338)

epsg3338 <- leaflet::leafletCRS(
  crsClass = "L.Proj.CRS",
  code = "EPSG:3338",
  proj4def =  "+proj=aea +lat_1=55 +lat_2=65 +lat_0=50 +lon_0=-154 +x_0=0 +y_0=0 +ellps=GRS80 +towgs84=0,0,0,0,0,0,0 +units=m +no_defs",
  resolutions = 2^(16:7))
```

```{r}
pop_region_4326 <- pop_region_3338 %>% 
  st_transform(crs=4326)
```

```{r}
m <- leaflet(options = leafletOptions(crs = epsg3338)) %>%
        addPolygons(data = pop_region_4326, 
                    fillColor = "gray",
                    weight = 1)

m
```

```{r}
pal <- colorNumeric(palette = "Reds", domain = pop_region_4326$total_pop)

m <- leaflet(options = leafletOptions(crs = epsg3338)) %>%
        addPolygons(data = pop_region_4326, 
                    fillColor = ~pal(total_pop),
                    weight = 1,
                    color = "black",
                    fillOpacity = 1,
                    label = ~region) %>% 
        addLegend(position = "bottomleft",
                  pal = pal,
                  values = range(pop_region_4326$total_pop),
                  title = "Total Population")

m
```

